version: '3.8'
services:
  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      - AUTH_URL=http://auth:3001
      - HISTORY_URL=http://history:3002
      - FORUM_URL=http://forum:3003

      
    depends_on:
      - auth
      - history
      - forum
    networks:
      - red_fixnow

  auth:
    build:
      context: ./AuthManagment
      dockerfile: Dockerfile
    networks:
      - red_fixnow

  history:
    build:
      context: ./HistoryManagment
      dockerfile: Dockerfile
    networks:
      - red_fixnow

  forum:
    build:
      context: ./ForumManagment
      dockerfile: Dockerfile
    networks:
      - red_fixnow

networks:
  red_fixnow:
    driver: bridge
