version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Gateway expuesto en el puerto 3000
    depends_on:
      - auth
      - history
      - forum
    networks:
      - red_fixnow

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - red_fixnow

  history:
    build:
      context: ./history
      dockerfile: Dockerfile
    networks:
      - red_fixnow

  forum:
    build:
      context: ./forum
      dockerfile: Dockerfile
    networks:
      - red_fixnow

networks:
  red_fixnow:
    driver: bridge
